package com.student.Emp_Db_App.models;

public enum Job {
    DATA_ANALYTYST, MANAGER, SECRETARY, BOSS, JUNIOR_JAVA_DEVELOPER, SENIOR_JAVA_DEVELOPER,
    PROJECT_MANAGER, HR_SPECIALIST, TEST_ENGINEER, MARKETING_SPECIALIST;
}
